# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_auto_20171020_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='log_app.User'),
        ),
    ]
